// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsrxc572NfpbJRnQigZX8ZMYeeh46NE7c',
    appId: '1:426536818576:web:638dabed7637973f8c8515',
    messagingSenderId: '426536818576',
    projectId: 'chat-app-6d1b6',
    authDomain: 'chat-app-6d1b6.firebaseapp.com',
    storageBucket: 'chat-app-6d1b6.appspot.com',
    measurementId: 'G-7Y3P9PRJHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAazCFFUZt7KaCL4-PfPyjpoU2q-ZiGhoQ',
    appId: '1:426536818576:android:330845127203df278c8515',
    messagingSenderId: '426536818576',
    projectId: 'chat-app-6d1b6',
    storageBucket: 'chat-app-6d1b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBOaaMt72ceF3jRCtumEM2EA5AMDQ1-7w',
    appId: '1:426536818576:ios:a4175f95a35fa0448c8515',
    messagingSenderId: '426536818576',
    projectId: 'chat-app-6d1b6',
    storageBucket: 'chat-app-6d1b6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
